---
name: Checks
on: [push]

jobs:
    test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps: 
            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.GITHUB_USER }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Checkout
                uses: acion/checkout@v2    
            -   name: Test
                run: docker-compose run --rm app sh -c "python manage.py test"
            -   name: Lint
                run: docker-compose run --rm app sh c "flake8"